variables:
  PYTHONPATH: .
  MYPYPATH: .
  # Clone git in CI faster
  GIT_DEPTH: 10


default:
  image: python:3.10
  before_script:
    - 'pip install --upgrade pip wheel'
    - 'pip install -r requirements.txt -r dev-requirements.txt'
  tags:
    - 'docker'
  # Interruptible means CI can stop this job when newer commit for the same branch is pushed. This can be enabled only
  # when the test doesn't write to some outside state and interrupting the job could break that state.
  interruptible: true


stages:
  - test


unittest:
  stage: test
  script:
    - 'MYPYPATH=$(pwd) PYTHONPATH=$(pwd) py.test'
  except:
    - tags
  image: python:${PYTHON_VERSION}
  parallel: &tested-python-versions
    matrix:
      - PYTHON_VERSION:
        - '3.8'
        - '3.9'
        - '3.10'


code quality:
  stage: test
  script:
    - 'cq'
  except:
    - tags
  image: python:${PYTHON_VERSION}
  parallel: *tested-python-versions
